### ISSUE TITLE
Upload over 5Gb files

### ISSUE THREAD

**Issue by nicolasbriant** [didinj/grails3-aws-s3-file-upload#1]
Hi, thanks for the code, it works great but I don't seem to be able to upload files larger than 5Gb.
I understand that this is a limitation of the AWS API, but I though using multiparts resolved the problem.

Would you have any advise?
Thanks
Nic

**Comment by didinj** [comment]
Did you add this line to application.yml?

```
controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 1000000
            maxRequestSize: 1000000
```
